### PR TITLE
[UI/INPUT] bugfix & commenting UIRenderFeature.UIElementUnderMouseCursor

### PR DESCRIPTION
**Pull request by CharlesWoodhill**
# PR Details

previous determination of the element was in a loop, so the last loop won (loop over UIComponents?).
now all loops are taken into account, and the last processed UIComponent that had a hit, will be taken. 
also created xml comment for the property.

## Description

moved the assignment of the public property outside and after the loop over UIComponents.

## Related Issue
#509

## Motivation and Context

it was buggy, it had to be fixed.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by CharlesWoodhill** [comment]
conflicts are maybe because i didnt delete/update my fork...
they are ok and can be marked as solved, i cant do that it seems.

**Comment by xen2** [comment]
@CharlesWoodhill You can try to merge latest `master` in your branch, and push again your branch in your repo.

**Comment by CharlesWoodhill** [comment]
Sorry had job in other country, back now, i hope this is ok now

**Comment by CharlesWoodhill** [comment]
no it wasnt, but now it should, sorry again git sometimes still confuses me :/

**Comment by CharlesWoodhill** [comment]
hello, can u plx merge this, i want to do more and need to update my branch from master tnx :)

**Comment by tebjan** [comment]
@CharlesWoodhill and @xen2 this merge leads to a build error... it conflicts with #573. It should be easy to fix though.

**Pull request merged**
