### PR TITLE
[WIP] Update SharpDX dependency to version 4.2.0

### PR DESCRIPTION
**Pull request by Venthe**
Update to latest SharpDX #34

**It is not yet tested.**, give me a few days. Pull request made to signal that someone is working :)

### CODE REVIEW

**Comment by xen2** [comment]
Thanks! Added WIP in title to reflect current state.

**Comment by Venthe** [comment]
@tebjan no, it's okay. I had a spare time; so I'll probably confirm it's working state & will wait for the new version for the merge

**Comment by xen2** [comment]
@tebjan Would it be OK to upgrade now for 3.1? Or you think better to keep version as low as possible?

**Comment by tebjan** [comment]
if the upgrade doesn't break anything, i think it's safe to go for it. it might well be the last SharpDX version since alexandre droppend support for it. so everyone will end up at this version sooner or later.

for us it would be a bit more easy to stay on the current version since we have third party dependencies that also use that one. but i can do a PR there as well to move up to 4.2. so go ahead, we will manage...

**Comment by dfkeenan** [comment]
It looks as if SharpDX has been updated to 4.2.0. @Xen2 should this PR request be closed?

**Comment by xen2** [comment]
Yes, thanks !
Updated to SharpDX 4.2.0 in latest 3.1 beta

**Pull request closed without merging**
