### PR TITLE
Fix the formating

### PR DESCRIPTION
**Pull request by migueldeicaza**

### CODE REVIEW

**Comment by tebjan** [comment]
hah, nice to see you here mr. @migueldeicaza. I'd interpret the fact that you show interest in this repository as a very good sign...

**Comment by SPTelur** [comment]
Wow... Can't believe it! Nice to see what you've done here, Sir...! 👍 

For Xenko team: I would suggest you guys to remove that annoying  CLA thingy. Sending PR(s) should be made enjoy.

**Comment by Kryptos-FR** [comment]
@SPTelur CLAs are very important because of copyright/trademark/patent issues. So no I can't be avoided.

On the other hand, you only need to sign it once (the first time) so it's not that much of a burden.

**Comment by xen2** [comment]
@migueldeicaza if you don't mind signing the CLA please, sorry for the bother!

**Comment by migueldeicaza** [comment]
Oops, just did now!

**Pull request merged**
