### PR TITLE
[Samples] Misc camera controller fixes

### PR DESCRIPTION
**Pull request by Eideren**
# PR Details
Fix BasicCameraController's mouse input, implements gamepad support, explain in detail common pitfalls of camera controller programming and fixes single frame lag on FPS sample's PlayerInput.

## Description
Redondant.

## Related Issue
None logged on Github.

## Motivation and Context
This mostly stemmed from this [Discord discussion](https://discordapp.com/channels/500285081265635328/500290856532574209/534784317319020555) I had a couple of weeks ago, creating this PR to fix the issue mentioned lower and clarify controller programming. This camera might very well be the first camera that users interact with, knowing that we might as well document thoroughly how it works and what users should do when modifying or creating one.

## Types of changes
- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Notes
- There still is at least one frame of lag somewhere else inside the engine, it is fairly visible when binding mouse input to a camera and looking at the OS cursor moving a fair amount of time before the in game camera does.
- I thought about modifying the first person camera to clarify it as well but that one's such a mess that I might as well rewrite it altogether.

### CODE REVIEW

**Comment by Eideren** [comment]
PR ready for review

**Comment by xen2** [comment]
Thanks! Tested in editor/new game, it seems to be much better than before.

**Comment by xen2** [comment]
Merging, thanks for the great work and well commented code!

**Comment by xen2** [comment]
Note: will cherry-pick this if we release a 3.0.0.8

**Comment by xen2** [comment]
@Eideren No need to fix this (or at least low priority and can be done separately), but except FPS sample, do you know if other samples will need a camera system rewrite?

**Pull request merged**
