### PR TITLE
[General] Simplify editor and presentation project files

### PR DESCRIPTION
**Pull request by Kryptos-FR**
# PR Details

## Description

Add rule patterns for .xaml, .xkfx, .png resources. It also reduces greatly some of the project files. For example, `Xenko.Assets.Presentation.csproj` and `Xenko.Core.Assets.Editor.csproj` size (number of lines) are divided by 5!

## Related Issue

None.

## Motivation and Context

Ease maintenance on project files and ensure newly added files follow the existing pattern (e.g. when adding a XAML control).

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Cleanup

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by xen2** [comment]
Great! I didn't like to have clean csproj for .cs files but lot of leftover for xaml/xksl files!
I am curious, reading "Motivation and Context" seems to imply adding new Xaml file will keep the csproj as is (without adding them like before), is it the case?

**Comment by Kryptos-FR** [comment]
In theory yes (and that was my intention). But it looks like Visual Studio is still adding the files to the .csproj. We should probably report it to Microsoft.

**Comment by xen2** [comment]
Did you try with VS2017 or VS2019?

**Comment by Kryptos-FR** [comment]
I did not try with VS2019, let me see.

**Comment by xen2** [comment]
@Kryptos-FR OK thanks.
It's not a big deal, the pros of doing those changes far out weight this minor inconvenience (esp if they fix it later)

**Comment by xen2** [comment]
Merging, thanks!

**Pull request merged**
