### PR TITLE
#34 Update to latest SharpDX

### PR DESCRIPTION
**Pull request by Line-**
Fix for issue #34 , updated SharpDX packages to latest stable

### CODE REVIEW

**Comment by xen2** [comment]
Thanks!

Doing a grep on the code, I could notice a few other locations. Can you fix them please?
```
Targets/Xenko.UWP.targets:    <PackageReference Include="SharpDX.Direct3D11" Version="4.0.1" />
Targets/Xenko.UWP.targets:    <PackageReference Include="SharpDX.D3DCompiler" Version="4.0.1" />
sources/core/Xenko.Core.Design/Xenko.Core.Design.csproj:    <PackageReference Include="SharpDX" Version="4.0.1" Condition="'$(TargetFramework)' == 'uap10.0'" />
sources/core/Xenko.Core.IO/Xenko.Core.IO.csproj:    <PackageReference Include="SharpDX" Version="4.0.1" Condition="'$(TargetFramework)' == 'uap10.0'" />
sources/editor/Xenko.GameStudio/Xenko.GameStudio.csproj:    <PackageReference Include="SharpDX" Version="4.0.1" />
sources/engine/Xenko.Assets/Xenko.Assets.csproj:    <PackageReference Include="SharpDX.Direct2D1" Version="4.0.1" />
sources/engine/Xenko.Games/Xenko.Games.csproj:    <PackageReference Include="SharpDX.Direct3D11" Version="4.0.1" Condition="'$(XenkoGraphicsApi)' == 'Direct3D11'" />
sources/engine/Xenko.Games/Xenko.Games.csproj:    <PackageReference Include="SharpDX.Direct3D12" Version="4.0.1" Condition="'$(XenkoGraphicsApi)' == 'Direct3D12'" />
sources/engine/Xenko.Graphics.ShaderCompiler/Xenko.Graphics.ShaderCompiler.csproj:    <PackageReference Include="SharpDX.D3DCompiler" Version="4.0.1" Condition="'$(XenkoPlatform)' == 'Windows'" />
sources/engine/Xenko.Graphics/Xenko.Graphics.csproj:    <PackageReference Include="SharpDX.Direct3D11" Version="4.0.1" Condition="'$(XenkoGraphicsApi)' == 'Direct3D11'" />
sources/engine/Xenko.Graphics/Xenko.Graphics.csproj:    <PackageReference Include="SharpDX.Direct3D12" Version="4.0.1" Condition="'$(XenkoGraphicsApi)' == 'Direct3D12'" />
sources/engine/Xenko.Graphics/Xenko.Graphics.csproj:    <PackageReference Include="SharpDX.D3DCompiler" Version="4.0.1" Condition="'$(XenkoGraphicsApi)' == 'Direct3D11' Or '$(XenkoGraphicsApi)' == 'Direct3D12'" />
sources/engine/Xenko.Input/Xenko.Input.csproj:    <PackageReference Include="SharpDX.RawInput" Version="4.0.1" Condition="'$(XenkoPlatform)' == 'Windows'" />
sources/engine/Xenko.Input/Xenko.Input.csproj:    <PackageReference Include="SharpDX.DirectInput" Version="4.0.1" Condition="'$(XenkoPlatform)' == 'Windows'" />
sources/engine/Xenko.Input/Xenko.Input.csproj:    <PackageReference Include="SharpDX.XInput" Version="4.0.1" Condition="'$(XenkoPlatform)' == 'Windows'" />
sources/engine/Xenko.Shaders.Compiler/Xenko.Shaders.Compiler.csproj:    <PackageReference Include="SharpDX.D3DCompiler" Version="4.0.1" Condition="'$(XenkoPlatform)' == 'Windows' Or '$(XenkoGraphicsApi)' == 'Direct3D11' Or '$(XenkoGraphicsApi)' == 'Direct3D12'" />
sources/engine/Xenko.Video/Xenko.Video.csproj:    <PackageReference Include="SharpDX.MediaFoundation" Version="4.0.1" Condition="'$(XenkoGraphicsApi)' == 'Direct3D11'" />
sources/engine/Xenko.Video/Xenko.Video.csproj:    <PackageReference Include="SharpDX.Direct3D11" Version="4.0.1" Condition="'$(XenkoGraphicsApi)' == 'Direct3D11'" />
sources/engine/Xenko.Video/Xenko.Video.csproj:    <PackageReference Include="SharpDX.Direct3D12" Version="4.0.1" Condition="'$(XenkoGraphicsApi)' == 'Direct3D12'" />
sources/engine/Xenko.VirtualReality/Xenko.VirtualReality.csproj:    <PackageReference Include="SharpDX.Direct3D11" Version="4.0.1" Condition="'$(XenkoGraphicsApi)' == 'Direct3D11'" />
sources/engine/Xenko/Xenko.csproj:    <PackageReference Include="SharpDX.Direct2D1" Version="4.0.1" Condition="'$(TargetFramework)' == 'uap10.0'" />
sources/tools/Xenko.Graphics.RenderDocPlugin/Xenko.Graphics.RenderDocPlugin.csproj:    <PackageReference Include="SharpDX.Direct3D11" Version="4.0.1" Condition="'$(XenkoGraphicsApi)' == 'Direct3D11'" />
```

**Comment by amerkoleci** [comment]
4.1.0 has some issues as changed the sharpgen part, better if you wait for 4.2.0 release

**Comment by Line-** [comment]
Thanks, I saw sharpdx/SharpDX#1048 and agree we should wait a little longer for 4.2.0 stable.

**Comment by tebjan** [comment]
If there is no absolute need for a specific feature or bugfix I would wait before forcing 4.2.0 on everyone... all third party projects used with Xenko will need to update then too.

**Comment by xen2** [comment]
Updated to SharpDX 4.2.0 in latest 3.1 beta (will be released in few minutes)

**Pull request closed without merging**
