### PR TITLE
Solving some typos in the spanish translation

### PR DESCRIPTION
**Pull request by meriaizen86**
# PR Details

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Kryptos-FR** [comment]
I'll have to reject it because you change the whole files. Please make sure to not concert line endings or encoding.

Also consider contributing to the Weblate project directly instead. That will ensure that you modify the latest version and keep in sync with every other contributors.

**Comment by Kryptos-FR** [comment]
@xen2 I don't see a link to Weblate in the readme. We should add one.

**Comment by meriaizen86** [comment]
I can't edit the locale files in my favourite text editor? :(

**Comment by shinkitsunemaru** [comment]
For the next time what kind of text encoding must I have to use?

**Comment by Kryptos-FR** [comment]
@meriaizen86 you can edit locally. But then we can run in this kind of situation were the files have not been properly modified.

Note that it could happen for any source files. Make sure that your git config is correct, especially `core.autocrlf` must be set to `true`.
See https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace and https://help.github.com/en/articles/dealing-with-line-endings

**Comment by xen2** [comment]
Unfortunately as @Kryptos-FR mentioned, I can't merge it if it introduce CRLF changes (it would confuse tools such as weblate).
Please either fix the CRLF or do the changes directly in weblate.

**Comment by Kryptos-FR** [comment]
Because the PR was created out of the master branch of @meriaizen86 it is now getting out of hand. It cannot be salvaged so I'm closing it.

**Pull request closed without merging**
