### PR TITLE
[Editor] Updated checkboxes for radiobuttons in ModelAssetTemplateWindow

### PR DESCRIPTION
**Pull request by xwellingtonx**
I resolved the issue #146, it was necessary to change the template of the radio button because the check icon was not being shown when the initial value was true, and about the UpdateStatus method, i removed because it is not necessary when used the GroupName in the elements.

### CODE REVIEW

**Comment by xwellingtonx** [comment]
@Kryptos-FR, This other account with my name, is not a github account I can not sign the license. Should I redo the PR to pull it off?

**Comment by Kryptos-FR** [comment]
@xwellingtonx 
* First make sure that your git config use the correct author/email.
* Then use git amend to redo the commit with the correct author: `git commit --amend --author="Your name <correct.name@email.com>"`
* Then force push your commit in the same branch as that PR, rewriting the whole history (make sure it is just a single commit in the end, don't include merge commit for example).

If those steps don't work. Close that PR and create a new one.

**Comment by xwellingtonx** [comment]
Thanks, now it's okay.

**Comment by xen2** [comment]
@Kryptos-FR is this PR good to merge?

**Comment by xen2** [comment]
@Kryptos-FR no worries, thanks for taking a look at it!

**Comment by xen2** [comment]
Merged, thanks!

**Comment by xwellingtonx** [comment]
Thanks, guys!

**Pull request merged**
