### PR TITLE
[Graphics] Add buffer initial counter offset

### LINKED ISSUE #122: Add initial counter offset value of compute shader
The initial counter value should be exposed and have a default of -1:

see for example:
https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Direct3D11/DeviceContext.ComputeShaderStage.cs#L65

for reference the issue from the old repo: https://github.com/SiliconStudio/xenko/issues/600

currently working on a pull request.

### PR DESCRIPTION
**Pull request by tebjan**
update of my previous pull request #123 which fixes #122 

@xen2 i fixed the signature for OpenGL and added a comment for DX12. most platforms don't seem to have proper uav support. solutions build properly here. tell me if something is missing.

### CODE REVIEW

**Comment by xen2** [comment]
Thanks!
I think there's still some CRLF issues (some lines were changed from CRLF to LF only).

**Comment by Kryptos-FR** [comment]
@xen2 Are you sure it is not your local git config that is incorrect? The default behavior on Windows has always been to "checkout windows-style, commit Unix-style", i.e. `core.autocrlf` set to `true` in the global `.git/config`. 
So I'm not sure how you could have a conflict on that. File on GitHub would always have LF line ending. Maybe I'm missing something...

**Comment by tebjan** [comment]
hm, that is weird, my git is set to "checkout as-is, commit as-is" so my git will never change any files. also my visual studio is set to CRLF. i hope the files are CRLF in the repo... or not?

**Comment by Kryptos-FR** [comment]
@tebjan No, as is usually the convention, files in the repo are LF. So "checkout as-is, commit as-is" is dangerous because it might keep mixed CRLF and LF line endings in the same file.

**Comment by xen2** [comment]
@Kryptos-FR I was also looking for a github status checker for CRLF but couldn't find anything. Could be handy because hard to notice!

**Comment by xen2** [comment]
@tebjan @Kryptos-FR OK what I have on my computer:
* `Buffer.Direct3D12.cs` (and any other file) on master: all CRLF (probably all LF on repo and autocrlf fixes it for me to CRLF)
* `Buffer.Direct3D12.cs` on your branch: all LF except the part you changed which are CRLF. I assume that's exactly how it is on the repo. It just come to me unmodified by autocrlf since it has a mix of CRLF and LF which is unexpected and git might think it's on purpose and important to keep.

**Comment by tebjan** [comment]
ok, makes perfect sense now. i'll change the settings for my local xenko get repo then. thanks for the input!

**Comment by xen2** [comment]
@tebjan are you going to fix the commit or should I do it on my side?

**Comment by tebjan** [comment]
yes, i'll fix that when i am back at the office. sorry for the delay, had a few days on vacation.

**Comment by xen2** [comment]
No worries, I don't mind doing it.

**Comment by tebjan** [comment]
@xen2 i did a reset on the branch and re-commited the files with git set to "checkout windows-style, commit Unix-style". hope the line endings are correct now.

**Comment by xen2** [comment]
LGTM, launching some tests and will merge.

**Comment by xen2** [comment]
Merged, thanks!

**Pull request merged**
